#!/bin/bash

FREERDP=freerdp2

function clearParams {
    mclient set $REGKEY/address ""
    mclient set $REGKEY/username ""
    mclient set $REGKEY/password ""
    mclient set $REGKEY/domain ""
    
    mclient set $REGKEY/authorizations/user/execution 0
    
    mclient commit
}

function getRegKey {
    # Get Template_UDS
    for key in `mclient get root/ConnectionType/${FREERDP}/connections | sed "s/dir //g"`; do
        val=`mclient get $key/label | sed "s/value //g"`
        if [ "$val" == "Template_UDS" ]; then
            REGKEY=$key
        fi
    done
}

function createUDSConnectionTemplate {
    mclient import /usr/share/uds/Template_UDS.xml
    mclient commit
}

ADDRESS=
USERNAME=
PASSWORD=
DOMAIN=
REGKEY=
CLEAR=0

# Try to locate registry key for UDS Template
getRegKey

if [ "$REGKEY" == "" ]; then
    # Not found, create on based on our template
    createUDSConnectionTemplate
    getRegKey
fi

for param in $@; do
    if [ "/u:" == "${param:0:3}" ]; then
        USERNAME=${param:3}
        CLEAR=1
    fi
    
    if [ "/p:" == "${param:0:3}" ]; then
        PASSWORD=${param:3}
        CLEAR=1
    fi
    
    if [ "/d:" == "${param:0:3}" ]; then
        DOMAIN=${param:3}
        CLEAR=1
    fi
    
    if [ "/v:" == "${param:0:3}" ]; then
        ADDRESS=${param:3}
        CLEAR=1
    fi
done

if [ "$CLEAR" -eq 1 ]; then
    clearParams
fi

ID=`basename $REGKEY`
RESPAWN=0

if [ "" != "$ADDRESS" ]; then
    mclient set $REGKEY/address "${ADDRESS}"
    RESPAWN=1
fi

if [ "" != "$USERNAME" ]; then
    mclient set $REGKEY/username "${USERNAME}"
    RESPAWN=1
fi

if [ "" != "$PASSWORD" ]; then
    mclient set $REGKEY/password "${PASSWORD}"
    RESPAWN=1
fi

if [ "" != "$DOMAIN" ]; then
    mclient set $REGKEY/domain "${DOMAIN}"
    RESPAWN=1
fi

if [ "$RESPAWN" -eq 1 ]; then
    mclient set $REGKEY/authorizations/user/execution 1
    mclient commit
    exec $0 # Restart without command line
fi

process-connection $ID

clearParams
