#!/bin/bash

. /etc/lsb-release

FREERDP=freerdp2


function clearParams {
    mclient set $REGKEY/address ""
    mclient set $REGKEY/username ""
    mclient set $REGKEY/password ""
    mclient set $REGKEY/domain ""
    
    mclient set $REGKEY/authorizations/user/execution 0
    
    mclient commit
}

function getRegKey {
    # Get Template_UDS
    for key in `mclient get root/ConnectionType/${FREERDP}/connections | sed "s/dir //g"`; do
        val=`mclient get $key/label | sed "s/value //g"`
        if [ "$val" == "Template_UDS" ]; then
            REGKEY=$key
        fi
    done
}

function createUDSConnectionTemplate {
    TMPFILE=$(mktemp /tmp/udsexport.XXXXXX)
  cat > $TMPFILE << EOF
<Profile>
 <ProfileSettings>
  <Name>HP-Profile-2026-04-20</Name>
  <RegistryRoot>root/ConnectionType/${FREERDP}/connections/{2883e457-74a1-49a7-9f77-3b56e02b937d}</RegistryRoot>
  <Target>
   <Hardware>t530</Hardware>
   <ImageId>T8X81022</ImageId>
   <Version>8.1.0</Version>
   <Config>standard</Config>
  </Target>
 </ProfileSettings>
 <ProfileRegistry>
  <NodeDir name="{2883e457-74a1-49a7-9f77-3b56e02b937d}">
   <NodeDir name="authorizations">
    <NodeDir name="user">
     <NodeKey name="edit">
      <NodeParam name="value">0</NodeParam>
      <NodeParam name="type">bool</NodeParam>
     </NodeKey>
     <NodeKey name="execution">
      <NodeParam name="value">0</NodeParam>
      <NodeParam name="type">bool</NodeParam>
     </NodeKey>
    </NodeDir>
   </NodeDir>
   <NodeKey name="label">
    <NodeParam name="value">Template_UDS</NodeParam>
    <NodeParam name="type">string</NodeParam>
   </NodeKey>
   <NodeKey name="credentialsType">
    <NodeParam name="value">password</NodeParam>
    <NodeParam name="type">string</NodeParam>
   </NodeKey>
   <NodeKey name="rdpEncryption">
    <NodeParam name="value">1</NodeParam>
    <NodeParam name="type">bool</NodeParam>
   </NodeKey>
   <NodeKey name="clipboardExtension">
    <NodeParam name="value">1</NodeParam>
    <NodeParam name="type">bool</NodeParam>
   </NodeKey>
   <NodeKey name="certificatePolicy">
    <NodeParam name="value">ignore</NodeParam>
    <NodeParam name="type">string</NodeParam>
   </NodeKey>
   <NodeKey name="portMapping">
    <NodeParam name="value">1</NodeParam>
    <NodeParam name="type">number</NodeParam>
   </NodeKey>
   <NodeKey name="localPartitionRedirection">
    <NodeParam name="value">1</NodeParam>
    <NodeParam name="type">number</NodeParam>
   </NodeKey>
   <NodeKey name="perfFlagNoWallpaper">
    <NodeParam name="value">0</NodeParam>
    <NodeParam name="type">number</NodeParam>
   </NodeKey>
   <NodeKey name="perfFlagFontSmoothing">
    <NodeParam name="value">1</NodeParam>
    <NodeParam name="type">number</NodeParam>
   </NodeKey>
   <NodeKey name="perfFlagDesktopComposition">
    <NodeParam name="value">1</NodeParam>
    <NodeParam name="type">number</NodeParam>
   </NodeKey>
   <NodeKey name="perfFlagNoWindowDrag">
    <NodeParam name="value">0</NodeParam>
    <NodeParam name="type">number</NodeParam>
   </NodeKey>
   <NodeKey name="perfFlagNoMenuAnimations">
    <NodeParam name="value">0</NodeParam>
    <NodeParam name="type">number</NodeParam>
   </NodeKey>
   <NodeKey name="perfFlagNoTheming">
    <NodeParam name="value">0</NodeParam>
    <NodeParam name="type">number</NodeParam>
   </NodeKey>
   <NodeKey name="hasDesktopIcon">
    <NodeParam name="value">0</NodeParam>
    <NodeParam name="type">bool</NodeParam>
   </NodeKey>
   <NodeKey name="address">
    <NodeParam name="value"/>
    <NodeParam name="type">string</NodeParam>
   </NodeKey>
   <NodeKey name="username">
    <NodeParam name="value"/>
    <NodeParam name="type">string</NodeParam>
   </NodeKey>
   <NodeKey name="password">
    <NodeParam name="value"/>
    <NodeParam name="type">encrypted</NodeParam>
   </NodeKey>
   <NodeKey name="domain">
    <NodeParam name="value"/>
    <NodeParam name="type">string</NodeParam>
   </NodeKey>
   <NodeKey name="iconPosition">
    <NodeParam name="value"/>
    <NodeParam name="type">string</NodeParam>
   </NodeKey>
  </NodeDir>
 </ProfileRegistry>
 <ProfileFiles/>
</Profile>
EOF
    mclient import $TMPFILE
    rm $TMPFILE
}

ADDRESS=
USERNAME=
PASSWORD=
DOMAIN=
REGKEY=
CLEAR=0

# Try to locate registry key for UDS Template
getRegKey

if [ "$REGKEY" == "" ]; then
    # Not found, create on based on our template
    createUDSConnectionTemplate
    getRegKey
fi

for param in $@; do
    if [ "/u:" == "${param:0:3}" ]; then
        USERNAME=${param:3}
        CLEAR=1
    fi
    
    if [ "/p:" == "${param:0:3}" ]; then
        PASSWORD=${param:3}
        CLEAR=1
    fi
    
    if [ "/d:" == "${param:0:3}" ]; then
        DOMAIN=${param:3}
        CLEAR=1
    fi
    
    if [ "/v:" == "${param:0:3}" ]; then
        ADDRESS=${param:3}
        CLEAR=1
    fi
done

if [ "$CLEAR" -eq 1 ]; then
    clearParams
fi

ID=`basename $REGKEY`
RESPAWN=0

if [ "" != "$ADDRESS" ]; then
    mclient set $REGKEY/address "${ADDRESS}"
    RESPAWN=1
fi

if [ "" != "$USERNAME" ]; then
    mclient set $REGKEY/username "${USERNAME}"
    RESPAWN=1
fi

if [ "" != "$PASSWORD" ]; then
    mclient set $REGKEY/password "${PASSWORD}"
    RESPAWN=1
fi

if [ "" != "$DOMAIN" ]; then
    mclient set $REGKEY/domain "${DOMAIN}"
    RESPAWN=1
fi

if [ "$RESPAWN" -eq 1 ]; then
    mclient set $REGKEY/authorizations/user/execution 1
    mclient commit
    exec $0 # Restart without command line
fi

process-connection $ID

clearParams
